spring:

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/example?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
mybatis:
   mapperLocations: classpath:/mapper/*.xml
